### ISSUE TITLE
test

### ISSUE THREAD

**Issue by CCZU-ZH** [JaehaKim97/SR4IR#2]
To start this test, I executed the following code "python src\main.py -opt options\seg\000_H2T.yml --test_only". But it says Start training. Is the path I specified wrong. It's urgent. I beg your advice

**Comment by JaehaKim97** [comment]
In our machine, the ```test_only``` mode works normally.

![image](https://github.com/JaehaKim97/SR4IR/assets/41074450/5c5cc279-d831-4d33-8d16-ffb064555086)

Could you please explain to me a more detailed situation?

**Comment by CCZU-ZH** [comment]
Thank you so much for taking the time to try and answer me.This is the result of my running, and there is also the test content, but I do not know why there is epoch and whether it is correct.

![591bef655bbe3e383e6a48cedeeb1b6](https://github.com/JaehaKim97/SR4IR/assets/153486776/22dffab8-b068-4894-9174-692d5519bcf8)

**Comment by JaehaKim97** [comment]
I guess ```--test_only``` flag is not working on your machine.
How about directly adding it as an option in the configuration file?

For example, you can edit ```options/seg/000_H2T.yml``` as following:

```
name: 000_H2T
...
deterministic: true
test_only: true # ***SET test_only OPTION AS TRUE IN HERE***

...

test:  
  batch_size: 1
  calculate_lpips: true
  visualize: true  # ***SET visualize OPTION AS TRUE IN HERE***
```

Then you can do the same thing with only this command: ```python src/main.py -opt options/seg/000_H2T.yml```.
